// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZmCBFF_DPYPTOzFJu5UvAVnM_8s26V2k',
    appId: '1:706849939010:web:5f5575a8935f212c2997db',
    messagingSenderId: '706849939010',
    projectId: 'bti-test-flutter',
    authDomain: 'bti-test-flutter.firebaseapp.com',
    storageBucket: 'bti-test-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7RYIngCiD4NbKJRNCizPZQJ8FFdpdGuE',
    appId: '1:706849939010:android:a393f44885aeba632997db',
    messagingSenderId: '706849939010',
    projectId: 'bti-test-flutter',
    storageBucket: 'bti-test-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmAlXjLO7SAE8ues7CO-n7M_-_iu5Rnd8',
    appId: '1:706849939010:ios:e319d780eb1b1fc42997db',
    messagingSenderId: '706849939010',
    projectId: 'bti-test-flutter',
    storageBucket: 'bti-test-flutter.firebasestorage.app',
    iosBundleId: 'com.example.technicalTestBti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmAlXjLO7SAE8ues7CO-n7M_-_iu5Rnd8',
    appId: '1:706849939010:ios:e319d780eb1b1fc42997db',
    messagingSenderId: '706849939010',
    projectId: 'bti-test-flutter',
    storageBucket: 'bti-test-flutter.firebasestorage.app',
    iosBundleId: 'com.example.technicalTestBti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZmCBFF_DPYPTOzFJu5UvAVnM_8s26V2k',
    appId: '1:706849939010:web:4e06f10a2d2c84112997db',
    messagingSenderId: '706849939010',
    projectId: 'bti-test-flutter',
    authDomain: 'bti-test-flutter.firebaseapp.com',
    storageBucket: 'bti-test-flutter.firebasestorage.app',
  );
}
